version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.09.1
    steps:
      - checkout
      - run:
          name: Instalar Java 17
          command: sudo apt install openjdk-17-jdk -y
      - run:
          name: Instalar Maven
          command: sudo apt install maven -y
      - run:
          name: Compilar aplicación
          command: mvn clean package -Dmaven.test.skip
      - persist_to_workspace:
          root: .
          paths:
            - target/*.jar  # Incluye cualquier archivo .jar generado

  deploy:
    executor: default-machine
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Transferir archivos a EC2
          command: |
            echo "${AWS_PRIVATE_KEY}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            scp -o StrictHostKeyChecking=no /workspace/target/*.jar ubuntu@${EC2_IP}:/home/ubuntu/BackArtistas/integracion-back/backend/target/
      - run:
          name: Reiniciar aplicación en EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@${EC2_IP} "pkill -f 'java -jar' || true"
            ssh -o StrictHostKeyChecking=no ubuntu@${EC2_IP} "nohup java -jar /home/ubuntu/BackArtistas/integracion-back/backend/target/*.jar > /home/ubuntu/BackArtistas/integracion-back/backend/target/app.log 2>&1 &"

workflows:
  build-and-deploy:
    jobs:
      - build  # Build en todas las ramas
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main  # Deploy solo en main
