version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Compilar aplicación
          command: cd backend && mvn clean package -Dmaven.test.skip
      - persist_to_workspace:
          root: .
          paths:
            - backend/target/*.jar # Incluye cualquier archivo .jar generado

  deploy:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - ${fingerprint}
      - attach_workspace:
          at: .
      - run:
          name: Transferir archivos a EC2
          command: |
            scp -o StrictHostKeyChecking=no backend/target/backend-0.0.1-SNAPSHOT.jar ubuntu@${EC2_IP}:/home/ubuntu/BackArtistas/integracion-back/backend/target/
      - run:
          name: Reiniciar aplicación en EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@${EC2_IP} "chmod +x /home/ubuntu/BackArtistas/integracion-back/backend/target/backend-0.0.1-SNAPSHOT.jar"
            ssh -v -o StrictHostKeyChecking=no ubuntu@${EC2_IP} "pkill -f 'java -jar' || true; echo 'pkill executed'"
            ssh -v -o StrictHostKeyChecking=no ubuntu@${EC2_IP} "nohup java -jar /home/ubuntu/BackArtistas/integracion-back/backend/target/backend-0.0.1-SNAPSHOT.jar > /home/ubuntu/BackArtistas/integracion-back/backend/target/app_output.log 2>&1 &"

workflows:
  build-and-deploy:
    jobs:
      - build # Build en todas las ramas
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main  # Deploy solo en main
