version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.09
      resource_class: xsmall
    steps:
      - checkout
      - run:
          name: Instalar Java 17
          command: sudo apt install openjdk-17-jdk -y
      - run:
          name: Instalar Maven
          command: sudo apt install maven -y
      - run:
          name: Compilar aplicación
          command: cd backend && mvn clean package -Dmaven.test.skip
      - persist_to_workspace:
          root: .
          paths:
            - backend/target/*.jar

  deploy:
    machine:
      image: ubuntu-2204:2023.09
      resource_class: xsmall
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Configure SSH Key
          command: |
            mkdir -p /tmp/ssh
            echo "${AWS_PRIVATE_KEY}" > /tmp/ssh/id_rsa
            chmod 600 /tmp/ssh/id_rsa
      - run:
          name: Transferir archivos a EC2
          command: |
            scp -i /tmp/ssh/id_rsa -o StrictHostKeyChecking=no backend/target/*.jar ubuntu@${EC2_IP}:/home/ubuntu/BackArtistas/integracion-back/backend/target/
      - run:
          name: Reiniciar aplicación en EC2
          command: |
            ssh -i /tmp/ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${EC2_IP} "pkill -f 'java -jar' || true"
            ssh -i /tmp/ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${EC2_IP} "nohup java -jar /home/ubuntu/BackArtistas/integracion-back/backend/target/*.jar > /home/ubuntu/BackArtistas/integracion-back/backend/target/app.log 2>&1 &"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main